baseURL = 'https://pablog.me/'
languageCode = 'es-es'
title = 'pablog.me'
theme = 'hugo-coder'
#ignoreLogs = ['warning-goldmark-raw-html']

defaultContentLanguage = "es-es"
paginate = 16
enableEmoji = true

[services]
[services.disqus]
shortname = "pablogme"

[params.telegram] # https://comments.app/
siteID = "6qMESLbM"
limit = "5"
# height = ""
# color = ""
# dislikes = ""
# outlined = ""
# colorful = ""
# dark = ""

[markup.highlight]
noClasses = false


[markup.goldmark.renderer]
unsafe = true

[params]
author = "Pablo Castellano"
license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Blog de Pablo Castellano"
keywords = "blog,free software,devops,librebor,libreborme"
info = ["Freelance Software Engineer and DevOps"]
avatarURL = "img/avatar1.jpg"
dateFormat = "2, January 2006"
since = 2009
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[params.matomo]
siteID = "2"
serverURL = "matomo.pablog.me"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/PabloCastellano/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 2
url = "https://twitter.com/_pablog/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/pablo-castellano-568549111/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About me"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Contact"
weight = 3
url = "contact/"

[languages.es-es]
languageName = ":es:"

[[languages.es-es.menu.main]]
name = "Sobre mí"
weight = 1
url = "about/"

[[languages.es-es.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.es-es.menu.main]]
name = "Contacto"
weight = 3
url = "contact/"
